#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Boels Verleih — branch selection.

Reads boels_candidates.json and picks ONE best branch per seoCity,
then generates an INSERT SQL file for review.

Selection rules (in priority order):
  1. Prefer depots with a real `depot.NNN@boels.de` email (skip generic like baulog@)
  2. Prefer exact city slug match in URL tail (e.g. tail == 'potsdam')
  3. Prefer shortest URL tail (usually the "main" depot)

Output:
  - boels_selected.json (one branch per city, curated)
  - boels_insert.sql    (INSERT INTO companies + company_cranes)
"""
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

HERE = os.path.dirname(__file__)
IN_FILE = os.path.join(HERE, "boels_candidates.json")
OUT_JSON = os.path.join(HERE, "boels_selected.json")
OUT_SQL = os.path.join(HERE, "boels_insert.sql")

DEPOT_EMAIL_RE = re.compile(r"^depot\.\d+@boels\.de$", re.IGNORECASE)


def score(branch: dict) -> tuple:
    """Lower score = better. Sort tuple: (no_depot_email, not_exact_slug, tail_len)."""
    tail = branch["url"].rsplit("/", 1)[-1]
    slug = branch["seo_city_slug"]
    email = (branch.get("email") or "").lower()
    has_depot_email = 1 if not DEPOT_EMAIL_RE.match(email) else 0
    is_exact = 0 if tail == slug else 1
    return (has_depot_email, is_exact, len(tail))


def escape_sql(s) -> str:
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def slugify(name: str, city: str) -> str:
    """Create a unique company slug: boels-verleih-gmbh-<city>[-<suffix>]"""
    base = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return base


def main():
    with open(IN_FILE, encoding="utf-8") as f:
        candidates = json.load(f)

    # Group by city
    by_city: dict[str, list[dict]] = {}
    for c in candidates:
        by_city.setdefault(c["seo_city_slug"], []).append(c)

    # Pick best per city
    selected: list[dict] = []
    for slug, group in sorted(by_city.items()):
        group.sort(key=score)
        best = group[0]
        selected.append(best)
        print(f"  {slug:22} → {best['url'].rsplit('/', 1)[-1]:35} email={best.get('email') or '—':25} zip={best.get('zip')}")

    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(selected, f, ensure_ascii=False, indent=2)
    print(f"\nSelected {len(selected)} branches → {OUT_JSON}")

    # Generate SQL
    sql_lines = [
        "-- Boels Verleih bulk import: one branch per seoCity (Minikran)",
        "-- Generated by boels_select.py — review before executing.",
        "",
        "BEGIN;",
        "",
    ]

    # Fallback hours if branch page didn't expose OpeningHoursSpecification
    STANDARD_HOURS = "Mo-Fr 7:00-16:30 | Sa 8:00-12:30 | So geschlossen"
    NAME = "Boels Verleih GmbH"

    for b in selected:
        city_name = b["seo_city_name"]
        city_slug = b["seo_city_slug"]
        state = b["seo_city_state"]
        slug = f"boels-verleih-{city_slug}"
        zip_code = b.get("zip")
        street = b.get("street")
        phone = b.get("phone")
        email = (b.get("email") or "").lower() or None
        if email and not DEPOT_EMAIL_RE.match(email):
            email = None
        lat = b.get("lat")
        lng = b.get("lng")
        website = b["url"]
        # Use real hours from JSON-LD; fallback to STANDARD_HOURS if the page
        # didn't expose any, or if all days came through as "geschlossen"
        # (Boels data bug on a few branches, e.g. nuernberg-west).
        raw_hours = b.get("opening_hours")
        if raw_hours and "Mo-So geschlossen" not in raw_hours:
            opening_hours = raw_hours
        else:
            opening_hours = STANDARD_HOURS
        # Full address like existing rows: "<street>, <zip> <city>"
        if street and zip_code:
            address = f"{street}, {zip_code} {city_name}"
        else:
            address = street
        description = (
            f"Boels Verleih GmbH in {city_name}. Minikranvermietung und "
            f"Baumaschinenverleih. Minikrane zur Miete für enge Baustellen, "
            f"Innenräume und Glasmontage."
        )

        sql_lines.append(
            "INSERT INTO companies (name, slug, description, website, phone, email, "
            "address, city, state, zip, lat, lng, opening_hours, "
            "is_premium, is_verified, is_active, is_relevant, google_reviews_count) VALUES ("
            f"{escape_sql(NAME)}, "
            f"{escape_sql(slug)}, "
            f"{escape_sql(description)}, "
            f"{escape_sql(website)}, "
            f"{escape_sql(phone)}, "
            f"{escape_sql(email)}, "
            f"{escape_sql(address)}, "
            f"{escape_sql(city_name)}, "
            f"{escape_sql(state)}, "
            f"{escape_sql(zip_code)}, "
            f"{lat if lat is not None else 'NULL'}, "
            f"{lng if lng is not None else 'NULL'}, "
            f"{escape_sql(opening_hours)}, "
            "false, false, true, true, 0);"
        )
        # Link Minikran (crane_types.slug = 'minikran-mieten')
        sql_lines.append(
            "INSERT INTO company_cranes (company_id, crane_type_id, has_operator, "
            "has_glass_sucker, electric) "
            f"SELECT c.id, ct.id, false, false, false "
            f"FROM companies c, crane_types ct "
            f"WHERE c.slug = {escape_sql(slug)} AND ct.slug = 'minikran-mieten';"
        )
        sql_lines.append("")

    sql_lines.append("COMMIT;")

    with open(OUT_SQL, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))
    print(f"Wrote SQL → {OUT_SQL}")


if __name__ == "__main__":
    main()
