"""
Import enrichment results from CSV into Supabase.

Usage:
  python scripts/import_enrichment.py --dry-run    # Show what would change (no DB writes)
  python scripts/import_enrichment.py               # Apply changes to Supabase

Reads: scripts/enrichment_results.csv
"""

import csv
import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / ".env.local")

SUPABASE_URL = os.environ["NEXT_PUBLIC_SUPABASE_URL"]
SUPABASE_KEY = os.environ["NEXT_PUBLIC_SUPABASE_ANON_KEY"]

CSV_PATH = Path(__file__).parent / "enrichment_results.csv"

CRANE_TYPE_MAP = {
    "minikran": "1a7019bd-7fd3-401a-8713-7f6be6fbd827",
    "autokran": "ab511eea-d464-47b9-8ada-16931dab5078",
    "dachdeckerkran": "99e6ce74-f707-494e-afc8-31627b3bf41d",
    "raupenkran": "0b61b867-53a6-4cf9-afbb-50c610dc4a2a",
    "anhaengerkran": "ef7ed422-402e-4553-9c01-661df28c66fc",
    "mobilkran": "02dc05de-6699-4849-93fb-2b655177bfd9",
    "baukran": "f1f86ce7-14b8-48ce-9004-5db8dde53949",
    "ladekran": "a556dcad-e379-4ac3-8d72-6eed094900d1",
}


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing")
    args = parser.parse_args()

    # ── Load CSV ──────────────────────────────────────────────
    with open(CSV_PATH, "r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    print(f"Loaded {len(rows)} rows from CSV")

    # ── Categorize ────────────────────────────────────────────
    ok_rows = [r for r in rows if r["crawl_status"] == "ok"]
    failed_rows = [r for r in rows if r["crawl_status"] != "ok"]

    with_types = [r for r in ok_rows if r["crane_types"]]
    with_desc = [r for r in ok_rows if r["description"]]
    with_hours = [r for r in ok_rows if r["opening_hours"]]
    with_prices = [r for r in ok_rows if r["price_day_min"]]

    print(f"\n{'='*50}")
    print(f"IMPORT PLAN:")
    print(f"  Crane types:     {len(with_types)} firms")
    print(f"  Descriptions:    {len(with_desc)} firms")
    print(f"  Opening hours:   {len(with_hours)} firms")
    print(f"  Prices:          {len(with_prices)} firms")
    print(f"  Failed (nullify website): {len(failed_rows)} firms")
    print(f"{'='*50}\n")

    if args.dry_run:
        print("--- DRY RUN --- No changes will be made.\n")

    # ── Connect to Supabase ───────────────────────────────────
    # We generate SQL since anon key can't UPDATE (RLS).
    # Output SQL file for Supabase Dashboard.

    sql_lines = []
    sql_lines.append("-- Enrichment import generated by import_enrichment.py")
    sql_lines.append(f"-- Date: {__import__('datetime').datetime.now().isoformat()}")
    sql_lines.append(f"-- Source: {CSV_PATH.name}")
    sql_lines.append("")

    # ── 1. Crane types (INSERT into company_cranes) ───────────
    # First check which companies already have crane types
    # We'll use a conditional: only insert if not exists
    crane_inserts = 0
    sql_lines.append("-- ============================================")
    sql_lines.append(f"-- 1. CRANE TYPES ({len(with_types)} firms)")
    sql_lines.append("--    Only inserts if company has NO existing crane types")
    sql_lines.append("-- ============================================")
    sql_lines.append("")

    for r in with_types:
        company_id = r["company_id"]
        types = [t.strip() for t in r["crane_types"].split(",") if t.strip() in CRANE_TYPE_MAP]
        if not types:
            continue

        # Conditional insert: only if company has no existing entries
        values = ", ".join(
            f"('{company_id}'::uuid, '{CRANE_TYPE_MAP[t]}'::uuid)"
            for t in types
        )
        sql_lines.append(f"-- {r['name']} ({r['city']}): {', '.join(types)}")
        sql_lines.append(f"INSERT INTO company_cranes (company_id, crane_type_id)")
        sql_lines.append(f"SELECT v.company_id, v.crane_type_id FROM (VALUES {values}) AS v(company_id, crane_type_id)")
        sql_lines.append(f"WHERE NOT EXISTS (SELECT 1 FROM company_cranes cc WHERE cc.company_id = '{company_id}'::uuid);")
        sql_lines.append("")
        crane_inserts += len(types)

    # ── 2. Descriptions ───────────────────────────────────────
    desc_updates = 0
    sql_lines.append("-- ============================================")
    sql_lines.append(f"-- 2. DESCRIPTIONS ({len(with_desc)} firms)")
    sql_lines.append("--    Overwrites existing generic descriptions")
    sql_lines.append("-- ============================================")
    sql_lines.append("")

    for r in with_desc:
        desc = r["description"].replace("'", "''")  # escape single quotes
        if not desc:
            continue
        sql_lines.append(f"UPDATE companies SET description = '{desc}' WHERE id = '{r['company_id']}';")
        desc_updates += 1

    sql_lines.append("")

    # ── 3. Opening hours ──────────────────────────────────────
    # We need a column for this — check if it exists, add if not
    hours_updates = 0
    if with_hours:
        sql_lines.append("-- ============================================")
        sql_lines.append(f"-- 3. OPENING HOURS ({len(with_hours)} firms)")
        sql_lines.append("-- ============================================")
        sql_lines.append("")
        sql_lines.append("-- Add column if not exists:")
        sql_lines.append("ALTER TABLE companies ADD COLUMN IF NOT EXISTS opening_hours TEXT DEFAULT NULL;")
        sql_lines.append("")

        for r in with_hours:
            hours = r["opening_hours"].replace("'", "''")
            if not hours:
                continue
            sql_lines.append(f"UPDATE companies SET opening_hours = '{hours}' WHERE id = '{r['company_id']}';")
            hours_updates += 1

        sql_lines.append("")

    # ── 4. Prices ─────────────────────────────────────────────
    price_updates = 0
    if with_prices:
        sql_lines.append("-- ============================================")
        sql_lines.append(f"-- 4. PRICES ({len(with_prices)} firms)")
        sql_lines.append("-- ============================================")
        sql_lines.append("")
        sql_lines.append("-- Add columns if not exist:")
        sql_lines.append("ALTER TABLE companies ADD COLUMN IF NOT EXISTS price_day_min INTEGER DEFAULT NULL;")
        sql_lines.append("ALTER TABLE companies ADD COLUMN IF NOT EXISTS price_day_max INTEGER DEFAULT NULL;")
        sql_lines.append("")

        for r in with_prices:
            p_min = r["price_day_min"]
            p_max = r["price_day_max"]
            sets = []
            if p_min:
                try:
                    sets.append(f"price_day_min = {int(float(p_min))}")
                except ValueError:
                    pass
            if p_max:
                try:
                    sets.append(f"price_day_max = {int(float(p_max))}")
                except ValueError:
                    pass
            if sets:
                sql_lines.append(f"UPDATE companies SET {', '.join(sets)} WHERE id = '{r['company_id']}';")
                price_updates += 1

        sql_lines.append("")

    # ── 5. Failed: nullify website ────────────────────────────
    if failed_rows:
        sql_lines.append("-- ============================================")
        sql_lines.append(f"-- 5. FAILED CRAWLS — set website = NULL ({len(failed_rows)} firms)")
        sql_lines.append("-- ============================================")
        sql_lines.append("")

        failed_ids = [f"'{r['company_id']}'" for r in failed_rows]
        sql_lines.append(f"UPDATE companies SET website = NULL WHERE id IN ({', '.join(failed_ids)});")
        sql_lines.append("")

    # ── Write SQL file ────────────────────────────────────────
    sql_path = Path(__file__).parent / "import_enrichment.sql"
    with open(sql_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"SQL file generated: {sql_path}")
    print(f"  Crane type inserts: {crane_inserts} rows for {len(with_types)} firms (conditional)")
    print(f"  Description updates: {desc_updates}")
    print(f"  Opening hours updates: {hours_updates}")
    print(f"  Price updates: {price_updates}")
    print(f"  Failed website nullify: {len(failed_rows)}")
    print(f"\nTotal SQL statements: {len([l for l in sql_lines if l.endswith(';')])}")
    print(f"\nFile size: {sql_path.stat().st_size / 1024:.1f} KB")

    if args.dry_run:
        print("\n--- DRY RUN complete. Review the SQL file, then run in Supabase SQL Editor. ---")
    else:
        print("\n⚠️  SQL file ready. Paste it into Supabase SQL Editor to apply.")
        print("    The anon key cannot run UPDATE/INSERT due to RLS.")


if __name__ == "__main__":
    main()
